---
services:
  aws.greengrass.Nucleus:
    version: "2.5.3"
  aws.greengrass.FleetProvisioningByClaim:
    configuration:
      rootPath: "/greengrass/v2"
      awsRegion: "us-east-1"
      iotDataEndpoint: "xxx"
      iotCredentialEndpoint: "xxx"
      iotRoleAlias: "MyTestGreenGrassRoleAlias"
      provisioningTemplate: "GreengrassFleetProvisioningTemplate"
      claimCertificatePath: "/greengrass/v2/certs/claim.pem.crt"
      claimCertificatePrivateKeyPath: "/greengrass/v2/certs/claim.private.pem.key"
      rootCaPath: "/greengrass/v2/AmazonRootCA1.pem"
      templateParameters:
        ThingName: "ThingName"
        ThingGroupName: "ThingGroupName"